### PR TITLE
msys2 ci

### PR DESCRIPTION
**Pull request by jeremyd2019**
Adds a separate job using setup-msys2 to test all currently available MinGW-w64 environments there.

These currently fail a few tests relating to signgam from lgamma.  I'm not sure if that's due to it calling mingw-w64's variant of lgamma or what.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
lgamma is in libmingwex, one of the default libs.  But, it should only be pulled in if the symbol is needed by something, and that shouldn't be if openlibm is providing it.

**Comment by jeremyd2019** [comment]
It could also be that it's pulling in mingw's signgam and openlibm's lgamma.  I'll have to investigate it locally to find out exactly what's going on

**Comment by jeremyd2019** [comment]
> It could also be that it's pulling in mingw's signgam and openlibm's lgamma. I'll have to investigate it locally to find out exactly what's going on

That seems to be the case, lgamma is exported from openlibm, but signgam is not.  Will probably have a patch quickly

**Comment by jeremyd2019** [comment]
couple more missing OLM_DLLEXPORTs it looks like

**Comment by jeremyd2019** [comment]
Finally all green!  Sorry for the bit of a mess on this PR.  I can squash some commits, and/or split the CI and fixes into separate PRs if preferred.

**Comment by jeremyd2019** [comment]
oh, the i686 clang fix I made in #242 uses is for `clang32`/`clang-i686`, which is "extra" experimental in that it's not even in the config files by default.  Adding the ability to test that in this CI would require extra special cases just for it.  I don't know if that's something you would care to have in your CI, given that it's so experimental upstream.

**Comment by ViralBShah** [comment]
Don't worry about the squashing. We can squash and merge.

**Comment by ViralBShah** [comment]
I think we don't need to have the experimental support in #242 in CI - just need to make sure it doesn't break anything else.

**Comment by DilumAluthge** [comment]
Thank you @jeremyd2019!

**Pull request merged**
