### PR TITLE
[DO NOT MERGE] log from musl

### PR DESCRIPTION
**Pull request by ViralBShah**
Just for experimenting for anyone who is interested. It appears to be slower than Julia's built-in log, which is in turn slower than the log that ships on mac. This is based on testing from Julia.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Also fma is significantly slower if enabled in clang. Yet to try with gcc.

**Comment by yuyichao** [comment]
For fma, did you compiled for correct arch?

**Comment by ViralBShah** [comment]
I assumed the compiler would pick the arch it was building on for starters.

**Comment by yuyichao** [comment]
I think compilers usually don’t do native arch by default

**Pull request closed without merging**
