### PR TITLE
CI: enable Windows x86

### PR DESCRIPTION
**Pull request by DilumAluthge**
Let's see what breaks.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @ViralBShah

**Comment by DilumAluthge** [comment]
@ViralBShah You'll need to approve workflows on this PR, since I've never contributed to this repo before.

If you want, you can relax that restriction by going to https://github.com/organizations/JuliaLang/settings/actions and, under the "Fork pull request workflows from outside collaborators" section, click the "Require approval for first-time contributors who are new to GitHub" option and click save.

**Comment by ViralBShah** [comment]
It's hard to tell what is actually breaking. Is it truly getting a 32-bit windows box?

**Comment by DilumAluthge** [comment]
I don't think GHA actually has 32-bit Windows VMs. We'll still be in a 64-bit Windows VM, but we can use a 32-bit compiler.

I'm going to try some of the advice from this thread: https://github.com/actions/virtual-environments/issues/2549

You'll need to re-approve the workflows.

**Comment by jeremyd2019** [comment]
I would recommend using the [setup-msys2 action](https://github.com/msys2/setup-msys2), but I don't know if that's reasonably possible in a single job matrixed with other OSes, I've generally seen a separate 'windows' job with a matrix for the different compilers (32/64-bit gcc/clang).  Also, if you want to be able to build for aarch64 using mingw, https://github.com/mstorsjo/llvm-mingw is probably the best choice.  I've been working on an arm64 environment for msys2, but currently that's all native, which currently means you'd need a self-hosted windows arm64 runner for github actions  ☹️(https://github.com/actions/runner/pull/785 )

**Comment by DilumAluthge** [comment]
I'm hoping that the latest fix I pushed will work. If not, I'll try the setup-msys action. We can choose to run it only on the Windows x86 job.

**Comment by jeremyd2019** [comment]
I'm not sure that relying on mingw toolchains from the pre-installed msys2 is going to continue to work once they update to the 2022 image.  https://github.com/actions/virtual-environments/issues/3949 (bottom of the table)

**Comment by DilumAluthge** [comment]
Ooof. In the short-term, we can just pin to the 2019 image. But you're right, it looks like we'll eventually need to use https://github.com/msys2/setup-msys2 for the 2022 image.

**Comment by DilumAluthge** [comment]
Thanks for the link to that table!

**Comment by ViralBShah** [comment]
Even with setup-msys2, I could only get 64-bit windows working. I'd you see my PR that I merged yesterday it has experimentation and logs with trying to enable msys2.

**Comment by jeremyd2019** [comment]
I think what's happening here is you can't really link with -nodefaultlibs on mingw-w64 (well you *can*, but there's a set of default libs you *need*).  See https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openlibm/01-mingw-build.patch for what they did to get it building there.

**Comment by ViralBShah** [comment]
Seems like we should adopt that patch from mingw.

**Comment by jeremyd2019** [comment]
I opened #243, don't know if that's preferred.  There are a few test failures that need figuring out though.

**Pull request closed without merging**
