### PR TITLE
Support for loongarch64 architecture

### PR DESCRIPTION
**Pull request by A1phaN**
Support for LoongArch64, a new ISA developed by Loongson Company which is already supported by glibc.

### CODE REVIEW

**Comment by loongson-zjl** [comment]
Could someone please review this pull request?

**Comment by oscardssmith** [comment]
From the perspective of someone who doesn't know anything about the architecture there's nothing that looks inherently unreasonable, but it's hard to review a PR for an architecture I've never heard of.

**Comment by loongson-zjl** [comment]
> From the perspective of someone who doesn't know anything about the architecture there's nothing that looks inherently unreasonable, but it's hard to review a PR for an architecture I've never heard of.

The LoongArch 'Loong64' architecture has been recently added to Debian Ports. However, there has been an issue with the openlibm package. (https://buildd.debian.org/status/package.php?p=openlibm&suite=sid)

We would like to add support for LoongArch in openlibm , is there anything specific that I should do to help address this issue?

Do we need any additional tests, documentation, or a specific environment to ensure that openlibm works well with LoongArch?

**Comment by loongson-zjl** [comment]
> Support for LoongArch64, a new ISA developed by Loongson Company which is already supported by glibc.
did you test in  a loongarch64 machine ?

**Comment by ViralBShah** [comment]
While I have no access to such machines, I don't see a challenge merging this - assuming the loongarch devs will maintain. Does it at least pass the bundled tests?

**Comment by ViralBShah** [comment]
If the tests are passing, can you also add a mention of the architecture to the README?

**Pull request merged**
