### PR TITLE
Add Windows testing with AppVeyor

### LINKED ISSUE #165: Test on AppVeyor
Would be nice to have this tested on a Windows CI as well.

### PR DESCRIPTION
**Pull request by ararslan**
This runs on my AppVeyor account to avoid using up the JuliaLang paid AV queue.

Closes #165.

### CODE REVIEW

**Comment by ararslan** [comment]
Windows 32-bit is working, but 64-bit says
```
set PATH=C:\MinGW\bin;%PATH%
mingw32-make.exe ARCH=%ARCH%
gcc   -fno-gnu89-inline -fno-builtin -O3 -fPIC -m64 -std=c99 -Wall -IC:/projects/openlibm -IC:/projects/openlibm/include -IC:/projects/openlibm/amd64 -IC:/projects/openlibm/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -IC:/projects/openlibm/ld80 -c src/common.c -o src/common.c.o
src/common.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 #include <openlibm_math.h>
 ^
src/common.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
Make.inc:145: recipe for target 'src/common.c.o' failed
mingw32-make.exe: *** [src/common.c.o] Error 1
Command exited with code 2
```

**Comment by ararslan** [comment]
Okay, I'm stumped.

**Comment by nalimilan** [comment]
> mingw32-make.exe ARCH=%ARCH%

Should it be `mingw64-make` on 64-bit?

**Comment by ViralBShah** [comment]
Any thoughts what needs to be done here?

**Comment by ararslan** [comment]
I haven't looked at this in quite a while. I still have no idea why it isn't working and I don't have access to a Windows machine or VM to test locally.

**Comment by ViralBShah** [comment]
Maybe disabling the 32-bit stuff so that the 64-bit stuff works would be still better. Right now appveyor just gives a red everywhere until we merge something here.

**Pull request merged**
